### ISSUE TITLE
Error in calc.effects/ sensmediation with mice

### ISSUE THREAD

**Issue by laurapavicic** [anitalindmark/Sensitivity_analysis#3]
Hello,
The following error occurrs when I try to run sensmediation: 
"Error in calc.effects(ML.object, type = "my", exp.name = exp.name, med.name = med.name,  : 
  The exposure is either missing from the outcome model or incorrectly named in exp.name (see documentation for exp.name in the sensmediation function)."

I checked the name of exp.name multiple times, I also made sure it is indeed a part of the outcome model. At some point, I thought the error occurs due to the multicategorical nature of my exposure, but I tried classifying exposure into 2 categories and had the same error again. I wonder if it is not a bug? 

I also wondered if it would be possible to use sensmediation with mids object from mice? I did not find any tutorials or useful advice online, so any reply is helpful. Thanks! 

Here is the prtscr of my code. In reality, meduc is a multicategorical variable and the model should be created with multinom, but I am not sure if sensmediation supports that.
![Capture d'écran 2024-04-23 204220](https://github.com/anitalindmark/Sensitivity_analysis/assets/113527139/550bbe95-c879-4eb5-9488-44060fc9faa7)

**Comment by anitalindmark** [comment]
Hello Laura,

The first thing I would check, if you have not done so already, is that exp.name given matches the name of the exposure in the output (from e.g., calling summary() on the model). E.g., if the exposure is coded as a factor (regardless of the number of levels) then the name in the output will not be the same as the name in the model specification in the function call which could lead to errors. If this is not the case, do get back to me with more details and I will investigate further. In addition, sensmediation currently only supports estimating effects contrasting two levels of a binary exposure variable so I would recommend sticking with the 2-category exposure variable.

I have not tried to use sensmediation in combination with multiple imputation but perhaps if you wrote a function that includes specifying the input models and outputting the sensmediation output that you want to combine then you could use with.mids(yourmidsobject, yourfunction()) and then pool() to pool the results and that could give you what you are looking for? Another option is to extract the imputed datasets from the mids object and run the analysis separately on each one and then pool using Rubin's rules.

No, unfortunately the only models supported by sensmediation are probit for binary outcomes and ols for continuous outcomes.

Kind regards,
Anita

From: laurapavicic ***@***.***>
Sent: den 23 april 2024 20:46
To: anitalindmark/Sensitivity_analysis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anitalindmark/Sensitivity_analysis] Error in calc.effects/ sensmediation with mice (Issue #3)


Hello,
The following error occurrs when I try to run sensmediation:
"Error in calc.effects(ML.object, type = "my", exp.name = exp.name, med.name = med.name, :
The exposure is either missing from the outcome model or incorrectly named in exp.name (see documentation for exp.name in the sensmediation function)."

I checked the name of exp.name multiple times, I also made sure it is indeed a part of the outcome model. At some point, I thought the error occurs due to the multicategorical nature of my exposure, but I tried classifying exposure into 2 categories and had the same error again. I wonder if it is not a bug?

I also wondered if it would be possible to use sensmediation with mids object from mice? I did not find any tutorials or useful advice online, so any reply is helpful. Thanks!

Here is the prtscr of my code. In reality, meduc is a multicategorical variable and the model should be created with multinom, but I am not sure if sensmediation supports that.
Capture.d.ecran.2024-04-23.204220.png (view on web)<https://github.com/anitalindmark/Sensitivity_analysis/assets/113527139/550bbe95-c879-4eb5-9488-44060fc9faa7>

-

**Comment by laurapavicic** [comment]
Hello Anita, 

Thank you so much for your prompt reply, it was helpful. I solved the error, it was indeed the wrong name of the exposure variable and not a bug.  Thank you for your ideas on how to use your package with mice, very insightful.  
I, unfortunately, won't be able to use sensmediation sensitivity analysis because my analyses have to be conducted using a multicategorical variable. 

I hope the package can be expanded to support multinomial logistic regression in the future.


Best regards, 

Laura

**Comment by anitalindmark** [comment]
I'm glad you solved the error. Hopefully the package can be expanded in the future to include more exposures, mediator and outcome types.
